# fly.toml app configuration file generated for riddle on 2023-08-11T21:15:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "riddle"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
